test.todo('tracks the height of the table body')
test.todo('getRowHeight gets the correct height')
test.todo('getTotalHeight correctly calculates total height of all rows')
test.todo('renders correct subset of rows')
test.todo('renders the correct rows when scrolling')
test.todo('clears state if new log file is loaded')
